### ISSUE TITLE
Separate KQ source code from the map editor into a different repo

### ISSUE THREAD

**Issue by ghost** [OnlineCop/kq-fork#10]
The source code for the map editor should be moved to it's own repo if possible.

**Comment by OnlineCop** [comment]
We now use [Tiled](https://www.mapeditor.org) for maps.

While a few hard-coded values remain (such as max entities on any given map), those as well have been ported to this new map format. The \*.tmx and \*.tsx files generated by Tiled is XML, so human-readable.
