### ISSUE TITLE
Using Tiled as the map editor instead of a custom map editor

### ISSUE THREAD

**Issue by ghost** [OnlineCop/kq-fork#11]
If possible, the current KQ map editor should be droped in favor or [**Tiled**](http://www.mapeditor.org/).

[**Tiled**](http://www.mapeditor.org/) is a powerful and mature FOSS map editor which should allow much better and complex editing of KQ.

**Comment by OnlineCop** [comment]
I believe Tiled is fully integrated on the [master](https://github.com/OnlineCop/kq-fork/tree/master) branch.
