### ISSUE TITLE
JSON or XML support

### ISSUE THREAD

**Issue by OnlineCop** [OnlineCop/kq-fork#32]
The proposed Tiled map format uses TMX, which uses an XML-formatted structure. It would be nice if a lot of our hard-coded values could be exported to an easier-to-read and easier-to-change format: XML or JSON. I guess we could also go a stronger LUA route, pushing as much as possible off into lua, although I prefer that data be kept in a more data-friendly format, and leave LUA to processing logic.

Two proposed JSON libraries were:
- https://github.com/udp/json-parser
- https://github.com/akheron/jansson

@peterhull90 indicated some familiarity with the former, stating that it was simply two files, `json.c` and `json.h`, that need be included. In a few local cases, I've tried to read in a JSON-formatted file using `udp/json-parser` with mixed results. From what I can gather, its strength is in reading JSON, but outputting JSON would require something else.

Online sources for C-based JSON libraries lead me to `jansson` although I have no experience with this. If it supports reading/writing and isn't too convoluted to get into place, it may be a good direction to go.

The other option is to look into storing data as XML. There is no shortage of C-based XML solutions out there, if we want to go that route instead.

**Comment by peterhull90** [comment]
From what I see the two are fairly similar in terms of reading JSON; `jansson` provides macros for a lot of things where `udp/json-parser` has direct structure access.
There is a companion project to `json-parser`, at [json-builder](https://github.com/udp/json-builder), which handles the output side. I haven't used it.

For KQ we'd be *mostly* reading with maybe writing for saved games and settings, do you agree? Also I don't think performance (speed) is a big issue for this project.

**Comment by peterhull90** [comment]
Also, just on the Lua option, this Lua:

    {name="Peter", height=1.7, keys={1,2,3}}

maps to this JSON:

    {"name": "Peter","height": 1.7,"keys": [1, 2, 3]}

Which is pretty straightforward. This doesn't help with TMX though.

**Comment by peterhull90** [comment]
Me again.
I note that jansson is available via `apt-get` on Linux whereas json-parser is not. So, go with jansson?

**Comment by OnlineCop** [comment]
Either is fine. If we choose any library, I would want to be able to encode and decode. Those two options were chosen specifically because they worked in pure C. If we plan to convert to C++ (#34), there may be other options as well that we can consider.

**Comment by OnlineCop** [comment]
Have we decided on a JSON parser? Is Jansson the library of choice? I'm going to rewrite most, if not all, data to be stored in JSON format. We could then get rid of the `PACKFILE` type, and any expected values that are not defined in the JSON file would just get default values.

**Comment by peterhull90** [comment]
I am away this weekend so am typing this into my phone ... I've been using
tinyxml2 to load the tiled maps and it's pretty good. I know xml is a bit
unfashionable at the moment but it would be easily possible to do what you
want in xml then we don't have two systems to worry about. Worth a thought.

**Comment by OnlineCop** [comment]
It looks like Tiled supports both XML and [JSON](https://github.com/bjorn/tiled/wiki/JSON-Map-Format) formats. I personally like JSON, but I'm not against going full XML. But I agree: I don't want to maintain both libraries when we can use one to do everything. Which one do you favor more: XML or JSON?

**Comment by peterhull90** [comment]
I'll see if I can code something up for Tiled JSON based on https://github.com/bjorn/tiled/wiki/JSON-Map-Format. I think XML is still the 'primary format' and then you export to JSON, so it's an extra step, but worth it if it makes things simpler for us.

**Comment by OnlineCop** [comment]
I was expecting the JSON version to actually be smaller than the XML version. Doesn't appear to be the case: town1.tmx is only `109,245` bytes, while the same map exported to JSON in Tiled came out to be `172,204`.
You've already got some of the XML format in place in your code, don't you? If so, let's keep going with that. While JSON seems to be "prettier" for me to read, if you have something working with tinyxml2 already, then no sense in ripping out that work and going with a non-standard format. Let's make map editing as painless as possible for future users: XML should be fine. I was just asking which format you personally prefer. If it's XML, let's go with XML. :-P

**Comment by peterhull90** [comment]
I've done a bit on it so far; it seems to be a bit hard going. I think the problem is Tiled's JSON format is a bit of an afterthought, for example JSON has string, boolean and numeric values, but if you have a properties block in a tiled map, all the properties are converted to strings. So this makes some of Jansson's nicer features unusable. Also, the tilesets (TSX files) don't seem to have an equivalent JSON format - there may be a way round this by making them internal and exporting them again, I haven't tried.
More later...

**Comment by OnlineCop** [comment]
I say we don't use JSON in the project at all then. We aren't using it currently, and it will be more of a headache to "tweak" tiled for JSON support than to just go full XML.

**Comment by peterhull90** [comment]
> I was expecting the JSON version to actually be smaller than the XML version.
I've left a space in the code to go to zipped tilemaps which will make the files a good deal smaller (e.g main.tmx goes from 731k to 101k, but that's the most extreme case). I haven't got around to it yet. I'm already using zlib as part of libpng so I hope it's possible to use that for compression.

**Comment by OnlineCop** [comment]
I may just be dumb, but if we went with tinyxml2, would we just copy the `tinyxml2.h` into `include/` and `tinyxml2.cpp` into `src/` and then add those to the build scripts? Or do we install them on the system somehow? I'm not braining today. (Running on ArchLinux, if that makes a difference.)

**Comment by uncleshelby** [comment]
I'm on Linux Mint, I just ran `apt-get install libtinyxml2-dev`. I think on Arch it you could just install the [tinyxml](https://www.archlinux.org/packages/community/x86_64/tinyxml/) package.

**Comment by OnlineCop** [comment]
I was able to install that version with `pacman -S tinyxml` but when recompiling the project, I get the error

`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
TINYXML2
    linked by target "kq-fork" in directory /home/onlinecop/kq-fork
`

So I'm guessing that it doesn't correlate `tinyxml` with `TINYXML2`?

**Comment by uncleshelby** [comment]
I think Arch's package is the correct tinyxml2, it just looks to me like the files are simply named `tinyxml.*`, since Arch mostly cares about bleeding edge and tinyxml1 isn't bleeding edge anymore. I think if you make symbolic links with tinyxml2 names, it should work.

I don't have an Arch installation right now, so I can't check. I'm just guessing this stuff from the [PKGBUILD](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/tinyxml).

**Comment by peterhull90** [comment]
Looks like we might have to create a `FindTINYXML2.cmake` file to do more sophisticated package searching - or just copy it in to the source repo as @OnlineCop  suggests.
