### ISSUE TITLE
Real fullscreen mode

### ISSUE THREAD

**Issue by ghost** [OnlineCop/kq-fork#5]
The "fullscreen" mode of the game currently just add black borders around the screen (at least on machine). This should be replaced by a true fullscreen mode.

**Comment by qubodup** [comment]
There appear to be fullscreen instructions in
https://wiki.allegro.cc/index.php?title=Creating_a_fullscreen_display_with_maximum/minimum_resolution

A relevant passage seem to be in src/setup.c line 296 (found via `grep full\ screen * -riI` )

Side note: I stretched to 4x by replacing '640, 480' with '1280, 960' in src/draw.c, src/setup.c, src/combat.c and recompiled.

**Comment by pedro-w** [comment]
I don't know what qualifies as a 'real fullscreen mode' but after #119 we're using SDL's fullscreen window which serves the same purpose.
