### ISSUE TITLE
Load/Save does not update properly

### ISSUE THREAD

**Issue by OnlineCop** [OnlineCop/kq-fork#58]
Commit hash 229f638, which is derived from the `peterhull90/xml` branch, allows a player to continue a saved game, which has been stored in XML format.

If a player saves to a new slot, then goes back to the Load/Save menu, the new save does not appear. The slot is only visible after restarting KQ.

After a player saves, reopening the Load/Save menu should show the changes to the save game slots properly.

**Comment by pedro-w** [comment]
This is fixed now isn't it?
